version: '3.8'

services:

  frontend:
    container_name: frontend
    image: cuaupro/alpr-system_frontend:latest  # Use the image from Docker Hub
    ports:
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/certs/https:/etc/nginx/certs
    networks:
      - alpr-network
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  backend:
    container_name: backend
    image: cuaupro/alpr-system_backend:latest  # Use the image from Docker Hub
    ports:
      - "8443:443"
    environment:
      - MQTT_BROKER=databus:8883
      - MQTT_SSL=true
    depends_on:
      - databus
    networks:
      - alpr-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 90M
    volumes:
      - ./backend/database:/app/backend/database
      - ./backend/certs:/app/backend/certs
      - ./backend/env:/app/backend/env


  gpio-handler:
    container_name: gpio-handler
    image: cuaupro/alpr-system_gpio-handler:latest  # Use the image from Docker Hub
    depends_on:
      - databus
    volumes:
      - ./gpio-handler/certs:/app/certs
      - ./gpio-handler/config.yaml:/app/config.yaml
    networks:
      - alpr-network
    runtime: nvidia
    environment:
      - JETSON_MODEL_NAME=JETSON_NANO
    devices:
      - /dev/gpiochip0
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  databus:
    container_name: databus
    restart: unless-stopped
    image: cuaupro/alpr-system_databus:latest  # Use the image from Docker Hub
    ports:
      - "8883:8883"
    volumes:
      - ./databus:/etc/mosquitto
    networks:
      - alpr-network
    hostname: "databus"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  ai-engine:
    container_name: ai-engine
    image: cuaupro/alpr-system_ai-engine:latest  # Use the image from Docker Hub
    depends_on:
      - databus
    runtime: nvidia
    networks:
      - alpr-network
    ports:
      - "8554:8554"
    volumes:
      - ./ai-engine/certs:/app/certs
      - ./ai-engine/config.yaml:/app/config.yaml
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 2G

networks:
  alpr-network:
