# MQTT client configuration
mqtt:
  broker: "databus"
  port: 8883
  clientId: "ai-engine" # Required. Must be unique on the MQTT broker
  auth: # Optional. Leave empty if no authentication is required
    username: ""
    password: ""
  tls: # Optional. Leave empty if no TLS is required
    enabled: true
    ca: "./certs/ca.crt"
    cert: "./certs/databus-ai-engine.crt"
    key: "./certs/databus-ai-engine.key"

# AI inference configuration
engine:
  network: "./engine/models/model-detect.onnx"
  class_labels: "./engine/models/labels-detect.txt"
  input_blob: "input_0"
  output_cvg: "scores"
  output_bbox: "boxes"
  width: 640
  height: 480
  threshold: 0.5
  ocr_model: "./engine/models/model-ocr.trt"
  headless: true

# Camera configuration
camera:
  - id: 1
    input_stream: "rtsp://@:8554/stream1" # URL of the first camera stream
    output_stream: "rtsp://@:8554/output1" # URL of the first camera output stream

# Logging configuration (optional)
logging:
  level: "info" # Log level: "debug", "info", "warn", "error", "fatal"
  print_to_stdout: False
  log_in_file: True