// This file is auto-generated by @hey-api/openapi-ts

export const $SigninRequest = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'johndoe'
        },
        password: {
            type: 'string',
            example: 'password123'
        }
    },
    required: ['username', 'password']
} as const;

export const $SigninResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'User signed in successfully'
        },
        token: {
            type: 'string',
            example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        },
        username: {
            type: 'string',
            example: 'johndoe'
        },
        firstName: {
            type: 'string',
            example: 'John'
        },
        lastName: {
            type: 'string',
            example: 'Doe'
        },
        role: {
            type: 'string',
            example: 'user'
        }
    }
} as const;

export const $SignupRequest = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            example: 'John'
        },
        lastName: {
            type: 'string',
            example: 'Doe'
        },
        username: {
            type: 'string',
            example: 'johndoe'
        },
        password: {
            type: 'string',
            example: 'password123'
        }
    },
    required: ['firstName', 'lastName', 'username', 'password']
} as const;

export const $SignupResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'User created successfully'
        },
        userId: {
            type: 'string',
            example: '12345'
        }
    }
} as const;

export const $ChangePasswordRequest = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            example: 'johndoe'
        },
        oldPassword: {
            type: 'string',
            example: 'oldpassword123'
        },
        newPassword: {
            type: 'string',
            example: 'newpassword123'
        }
    },
    required: ['username', 'oldPassword', 'newPassword']
} as const;

export const $ChangePasswordResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'Password changed successfully'
        }
    }
} as const;

export const $LicensePlateResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            example: '550e8400-e29b-41d4-a716-446655440000'
        },
        licensePlate: {
            type: 'string',
            example: 'ABC1234'
        },
        validFrom: {
            type: 'string',
            format: 'date',
            example: '2024-01-01'
        },
        validTo: {
            type: 'string',
            format: 'date',
            example: '2025-01-01'
        }
    }
} as const;

export const $LicensePlateRequest = {
    type: 'object',
    properties: {
        licensePlate: {
            type: 'string',
            example: 'ABC1234'
        },
        validFrom: {
            type: 'string',
            format: 'date',
            example: '2024-01-01'
        },
        validTo: {
            type: 'string',
            format: 'date',
            example: '2025-01-01'
        }
    },
    required: ['licensePlate', 'validFrom', 'validTo']
} as const;

export const $LicensePlateCreateResponse = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            example: '550e8400-e29b-41d4-a716-446655440000'
        },
        message: {
            type: 'string',
            example: 'License plate created successfully'
        }
    }
} as const;

export const $MessageResponse = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'Operation successful'
        }
    }
} as const;