// This file is auto-generated by @hey-api/openapi-ts

export type SigninRequest = {
    username: string;
    password: string;
};

export type SigninResponse = {
    message?: string;
    token?: string;
    username?: string;
    firstName?: string;
    lastName?: string;
    role?: string;
};

export type SignupRequest = {
    firstName: string;
    lastName: string;
    username: string;
    password: string;
};

export type SignupResponse = {
    message?: string;
    userId?: string;
};

export type ChangePasswordRequest = {
    username: string;
    oldPassword: string;
    newPassword: string;
};

export type ChangePasswordResponse = {
    message?: string;
};

export type LicensePlateResponse = {
    id?: string;
    licensePlate?: string;
    validFrom?: string;
    validTo?: string;
};

export type LicensePlateRequest = {
    licensePlate: string;
    validFrom: string;
    validTo: string;
};

export type LicensePlateCreateResponse = {
    id?: string;
    message?: string;
};

export type MessageResponse = {
    message?: string;
};

export type PostAuthSigninData = {
    requestBody: SigninRequest;
};

export type PostAuthSigninResponse = SigninResponse;

export type PostAuthSignupData = {
    requestBody: SignupRequest;
};

export type PostAuthSignupResponse = SignupResponse;

export type PostAuthChangePasswordData = {
    requestBody: ChangePasswordRequest;
};

export type PostAuthChangePasswordResponse = ChangePasswordResponse;

export type GetApiHealthcheckResponse = unknown;

export type GetApiLicensePlatesResponse = Array<LicensePlateResponse>;

export type PostApiLicensePlatesData = {
    requestBody: LicensePlateRequest;
};

export type PostApiLicensePlatesResponse = LicensePlateCreateResponse;

export type PutApiLicensePlatesByLicensePlateIdData = {
    /**
     * ID of the license plate to delete
     */
    licensePlateId: string;
    requestBody: LicensePlateRequest;
};

export type PutApiLicensePlatesByLicensePlateIdResponse = MessageResponse;

export type DeleteApiLicensePlatesByLicensePlateIdData = {
    /**
     * ID of the license plate to delete
     */
    licensePlateId: string;
};

export type DeleteApiLicensePlatesByLicensePlateIdResponse = MessageResponse;

export type PostApiLicensePlatesArchiveResponse = MessageResponse;

export type GetApiLicensePlatesArchiveResponse = Array<LicensePlateResponse>;

export type $OpenApiTs = {
    '/auth/signin': {
        post: {
            req: PostAuthSigninData;
            res: {
                /**
                 * Successful login
                 */
                200: SigninResponse;
                /**
                 * Unauthorized
                 */
                401: unknown;
            };
        };
    };
    '/auth/signup': {
        post: {
            req: PostAuthSignupData;
            res: {
                /**
                 * User created
                 */
                201: SignupResponse;
                /**
                 * Invalid input
                 */
                400: unknown;
            };
        };
    };
    '/auth/change-password': {
        post: {
            req: PostAuthChangePasswordData;
            res: {
                /**
                 * Password change successful
                 */
                200: ChangePasswordResponse;
                /**
                 * Invalid input or password
                 */
                400: unknown;
            };
        };
    };
    '/api/healthcheck': {
        get: {
            res: {
                /**
                 * App is up and running
                 */
                200: unknown;
                /**
                 * Invalid input
                 */
                400: unknown;
            };
        };
    };
    '/api/license-plates': {
        get: {
            res: {
                /**
                 * A list of license plates
                 */
                200: Array<LicensePlateResponse>;
                /**
                 * Invalid input
                 */
                400: unknown;
            };
        };
        post: {
            req: PostApiLicensePlatesData;
            res: {
                /**
                 * License plate created
                 */
                201: LicensePlateCreateResponse;
                /**
                 * Invalid input
                 */
                400: unknown;
            };
        };
    };
    '/api/license-plates/{licensePlateId}': {
        put: {
            req: PutApiLicensePlatesByLicensePlateIdData;
            res: {
                /**
                 * License plate updated
                 */
                200: MessageResponse;
                /**
                 * Invalid input
                 */
                400: unknown;
                /**
                 * License plate not found
                 */
                404: unknown;
            };
        };
        delete: {
            req: DeleteApiLicensePlatesByLicensePlateIdData;
            res: {
                /**
                 * License plate deleted
                 */
                200: MessageResponse;
                /**
                 * Invalid input
                 */
                400: unknown;
                /**
                 * License plate not found
                 */
                404: unknown;
            };
        };
    };
    '/api/license-plates/archive': {
        post: {
            res: {
                /**
                 * License plates archived
                 */
                200: MessageResponse;
                /**
                 * Invalid input
                 */
                400: unknown;
            };
        };
        get: {
            res: {
                /**
                 * A list of license plates
                 */
                200: Array<LicensePlateResponse>;
                /**
                 * Invalid input
                 */
                400: unknown;
            };
        };
    };
};