name: "Build GPIO Handler Docker Image"
on:
  push:
    branches:
      - main
    paths:
      - 'gpio-handler/**'

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths:
      - 'gpio-handler/**.py'
      - 'gpio-handler/**.txt'
      - 'gpio-handler/Dockerfile'
      - 'gpio-handler/requirements.txt'

jobs:

  build-gpio-handler:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # todo changeme
          images: CuAuPro/gpio-handler
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          file: ./gpio-handler/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max