# MQTT client configuration
mqtt:
  broker: "databus"
  port: 8883
  clientId: "gpio-handler" # Required. Must be unique on the MQTT broker
  auth: # Optional. Leave empty if no authentication is required
    username: ""
    password: ""
  tls: # Optional. Leave empty if no TLS is required
    enabled: true
    ca: "./certs/ca.crt"
    cert: "./certs/databus-gpio-handler.crt"
    key: "./certs/databus-gpio-handler.key"

# GPIO configuration for gate control
gate:
  # Closing settings
  ignore_duration: 20
  close:
    inverse: true # Optional. Invert the output signal
    pin: 17 # Optional. GPIO pin number
  # Opening settings
  open:
    inverse: false # Optional. Invert the output signal
    pin: 18 # Required. GPIO pin number
    duration: 5 # Duration in seconds to trigger ramp opening

# Logging configuration (optional)
logging:
  level: "info" # Log level: "debug", "info", "warn", "error", "fatal"
  print_to_stdout: False
  log_in_file: True